### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by krishdb38** [creativetimofficial/ct-argon-dashboard-pro-django#1]
there is argon v2 available for bootstrap and other js.
is there any Django argon V2 available soon or not?

why there are Django based templates are very low 

Thank you

**Comment by app-generator** [comment]
Hello @krishdb38 

Sorry for this late reply. Here are some news:

>This product was updated to a new codebase

- Theme-able UI (no longer hard coded inside the product)
- CI/CD flow (fast Deploy on render)

> V2 Version is available using the same pattern, but listed on [AppSeed.us](https://appseed.us/product/argon-dashboard2-pro/django/) (soon available also on `Creative-Tim`)

- Here are the sources [Django Argon Dashboard2](https://github.com/app-generator/django-argon-dashboard2-pro)
- [LIVE Demo](https://django-argon-dash2-pro.onrender.com/accounts/basic-login/)  

Let us know if you have further questions. 

Adrian @ `Creative-Tim` Support
